export const ItemId = {
    Steel: 1,
    Fury: 2,
    Lorekeeper: 3,
    WorldstoneShard: 4,
    Flash: 5,
    Titan: 6,
    Smoke: 7,
    Nexus: 8,
    Triumph: 9,
    Glory: 10,
    Grace: 11,
    Genesis: 12,
    Destiny: 13,
    Wrath: 14,
    Fortress: 15,
    Elder: 16,
    Pledge: 19,
    Flow: 20,
    GuidingLight: 21,
}