export const RuneId = {
    EL: 0,
    ELD: 1,
    TIR: 2,
    NEF: 3,
    ETH: 4,
    ITH: 5,
    TAL: 6,
    RAL: 7,
    ORT: 8,
    THUL: 9,
    AMN: 10,
    SOL: 11,
    SHAEL: 12,
    DOL: 13,
    HEL: 14,
    IO: 15,
    LUM: 16,
    KO: 17,
    FAL: 18,
    LEM: 19,
    PUL: 20,
    UM: 21,
    MAL: 22,
    IST: 23,
    GUL: 24,
    VEX: 25,
    OHM: 26,
    LO: 27,
    SUR: 28,
    BER: 29,
    JAH: 30,
    CHAM: 31,
    ZOD: 32,
}

export type Rune = keyof typeof RuneId
export type RuneID = number
export const RuneNames = Object.entries(RuneId).reduce((acc, [k, v]) => ({...acc, [v]: k}), {})